// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using amusinghoS.EntityData;

namespace amusinghoS.EntityData.Migrations
{
    [DbContext(typeof(amusinghoSDbContext))]
    [Migration("20200220103503_20201834")]
    partial class _20201834
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("amusinghoS.EntityData.Model.amusingArticle", b =>
                {
                    b.Property<Guid>("articleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreateTime")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DeleteId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DeleteTime")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("articleId");

                    b.ToTable("amusingArticles");
                });

            modelBuilder.Entity("amusinghoS.EntityData.Model.amusingHosUser", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(16) CHARACTER SET utf8mb4")
                        .HasMaxLength(16);

                    b.Property<string>("PassWord")
                        .HasColumnType("varchar(18) CHARACTER SET utf8mb4")
                        .HasMaxLength(18);

                    b.HasKey("userId");

                    b.ToTable("amusingHosUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
